-- Migração para integrar tabelas admin
USE TECHFIT_DB;

-- Verificar e adicionar colunas faltantes
ALTER TABLE ADMINISTRACAO 
ADD COLUMN IF NOT EXISTS ID_ADMINISTRADOR INT AUTO_INCREMENT PRIMARY KEY FIRST,
ADD COLUMN IF NOT EXISTS AUSER VARCHAR(80) NOT NULL AFTER ID_ADMINISTRADOR,
ADD COLUMN IF NOT EXISTS SENHA VARCHAR(255) NOT NULL AFTER AUSER;

-- Criar admin padrão (senha: admin123)
INSERT INTO ADMINISTRACAO (AUSER, SENHA) 
VALUES ('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi')
ON DUPLICATE KEY UPDATE AUSER = AUSER;

-- Verificar estrutura das tabelas
SHOW TABLES;
DESCRIBE ADMINISTRACAO;