CREATE DATABASE TECHFIT_DB;
USE TECHFIT_DB;


CREATE TABLE FILIAIS (
	ID_FILIAL INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO VARCHAR(100) NOT NULL,
    CARGA_MAX INT DEFAULT 50,
    NUM_COLABORADORES INT DEFAULT 0,
    CEP VARCHAR(15) NOT NULL
);

CREATE TABLE PROFESSORES (
	ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PROFESSOR VARCHAR(80) NOT NULL,
    CPF VARCHAR(14),
	ESPECIALIDADE VARCHAR(80) NOT NULL,
    FK_FILIAL INT,
   FOREIGN KEY (FK_FILIAL) REFERENCES FILIAIS(ID_FILIAL) 
);

CREATE TABLE AULAS (
	ID_AULA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_AULA VARCHAR(80) NOT NULL,
    TIPO_AULA VARCHAR(20) NOT NULL,
    TEMPO_AULA TIME NOT NULL,
    DATA_AULA DATETIME,
    FK_PROFESSOR INT,
    FOREIGN KEY (FK_PROFESSOR) REFERENCES PROFESSORES(ID_PROFESSOR)
);

	CREATE TABLE PLANOS (
		ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
		TIPO_PLANO VARCHAR(50) NOT NULL,
        DESCRICAO VARCHAR(255) NOT NULL,
        MAQUINAS VARCHAR(50) NOT NULL,
        AULAS_GRUPO VARCHAR(50) NOT NULL,
        TREINAMENTO VARCHAR(50) NOT NULL,
        CONSULTORIA VARCHAR(50) NOT NULL,
        T_AVALIACAO VARCHAR(50) NOT NULL,
        H_ACESSO VARCHAR(50) NOT NULL,
		PRECO DECIMAL(5,2) NOT NULL
);
    
CREATE TABLE ALUNOS (
	ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ALUNO VARCHAR(80) NOT NULL,
    IDADE DATE NOT NULL,
    ENDERECO_ALUNO VARCHAR(80) NOT NULL,
    TELEFONE VARCHAR(19),
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    FK_PLANO INT NULL,
    FK_AULA INT NULL,
    FOREIGN KEY (FK_PLANO) REFERENCES PLANOS(ID_PLANO),
    FOREIGN KEY (FK_AULA) REFERENCES AULAS(ID_AULA) 
);

CREATE TABLE AVALIACOES_FISICAS (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_AVALIACAO DATE NOT NULL,
    PESO DECIMAL(5,2) NOT NULL,
    ALTURA DECIMAL(4,2) NOT NULL,
    PEITORAL DECIMAL(5,2),
    CINTURA DECIMAL(5,2),
    QUADRIL DECIMAL(5,2),
    BRAÇO_ESQUERDO DECIMAL(5,2),
    BRAÇO_DIREITO DECIMAL(5,2),
    COXA DECIMAL(5,2),
    GORDURA_CORPORAL DECIMAL(5,2),
    MASSA_MEGRA DECIMAL(5,2),
    TMB DECIMAL(5,2),
    IMC DECIMAL(4,2),
    FK_ALUNO INT,
    FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
);

CREATE TABLE PRODUTOS (
	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(80) NOT NULL,
    QUANTIDADE INT DEFAULT 20,
    PSTATUS VARCHAR(13) DEFAULT 'DISPONÍVEL',
    PRECO DECIMAL(5,2)
);

CREATE TABLE ADMINISTRACAO(
	ID_ADMINISTRADOR INT AUTO_INCREMENT PRIMARY KEY,
    SENHA VARCHAR(255) NOT NULL,
    USER VARCHAR(50) NOT NULL
);

CREATE TABLE AGENDAMENTOS(
	ID_AGENDAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    FK_AULA INT,
    FK_ALUNO INT,
    FOREIGN KEY (FK_AULA) REFERENCES AULAS(ID_AULA),
     FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
);

insert into ADMINISTRACAO(senha, user) values ('admin', 'admin');


