CREATE DATABASE TECHFIT;
USE TECHFIT;

CREATE TABLE PROFESSORES (
	ID_PROFESSORES INT AUTO_INCREMENT,
    NOME_PROFESSOR VARCHAR(80) NOT NULL,
    CPF VARCHAR(14),
	ESPECIALIDADE VARCHAR(80) NOT NULL
);

CREATE TABLE ALUNOS (
	ID_ALUNOS INT AUTO_INCREMENT,
    NOME_ALUNO VARCHAR(80) NOT NULL,
    IDADE INT NOT NULL,
    ENDERECO_ALUNO VARCHAR(80) NOT NULL,
    TELEFONE VARCHAR(19),
    EMAIL VARCHAR(50) NOT NULL,
    AVALIACAO_FISICA VARCHAR(50) NOT NULL
);

CREATE TABLE FILIAS (
	ID_FILIAS INT AUTO_INCREMENT,
    ENDERECO VARCHAR(100) NOT NULL,
    CARGA_MAX INT DEFAULT 50,
    NUM_COLABORADORES INT DEFAULT 0,
    CEP VARCHAR(15) NOT NULL
);

CREATE TABLE PRODUTOS (
	ID_PRODUTOS INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(80) NOT NULL,
    QUANTIDADE INT DEFAULT 20,
    PSTATUS VARCHAR(13) DEFAULT 'DISPONÍVEL',
    PRECO DECIMAL(5,2)
);

CREATE TABLE ADMINISTRACAO (
	ID_ADMINISTRACAO INT AUTO_INCREMENT,
    SENHA VARCHAR(20) NOT NULL,
    AUSER VARCHAR(80) NOT NULL
);

CREATE TABLE RELATORIOS (
	ID_RELATORIO INT AUTO_INCREMENT,
    RELATORIO_FILIAS VARCHAR(255),
    RELATORIO_PROFESSOR VARCHAR(255),
    RELATORIO_AULA VARCHAR(255),
    RELATORIO_CLIENTE VARCHAR(255)
);